/**
 * Generates CODEMAP.md — a deterministic, machine-readable symbol index for
 * coding agents. Walks `src/` via the TypeScript Compiler API, extracts
 * signatures (not bodies), JSDoc, imports, and re-export edges, resolves
 * `src/index.ts` transitively through the TypeChecker, and emits one
 * sorted JSON document inside CODEMAP.md.
 *
 * Run: `npm run codemap`
 * Check: `npm run codemap:check` (exits non-zero if CODEMAP.md is stale)
 *
 * Hard constraints:
 * - Deterministic: same src/ → byte-identical CODEMAP.md
 * - No timestamps; staleness via sourceHash (sha256 of sorted file contents)
 * - No implementation bodies; signatures only
 * - No new runtime deps; uses `typescript` + Node built-ins only
 */
import * as ts from 'typescript';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { argv, cwd, exit, stderr, stdout } from 'node:process';

const REPO_ROOT = cwd();
const CONFIG_PATH = join(REPO_ROOT, 'codemap.config.json');
const OUTPUT_PATH = join(REPO_ROOT, 'CODEMAP.md');
const SCHEMA = 'codemap.v2';
const SIZE_WARN_BYTES = 150 * 1024;
const MAX_RESOLUTION_DEPTH = 8;
const MAX_JSDOC_LENGTH = 300;
const MAX_EXAMPLE_LENGTH = 80;
const MD_PREAMBLE =
  '# CODEMAP\n\nMachine-readable symbol index. Generated by `npm run codemap`. Do not edit by hand.\n\n';
const FENCE_OPEN = '```json\n';
const FENCE_CLOSE = '\n```\n';

interface CodemapConfig {
  sourceDirs: string[];
  entrypoints: string[];
  exclude: string[];
  maxSignatureLength: number;
}

interface PackageJson {
  name?: string;
  version?: string;
}

interface PublicApiEntry {
  name: string;
  kind: string;
  file: string;
  line: number;
  signature: string;
  jsdoc?: string;
  typeOnly: boolean;
}

interface ClassMember {
  name: string;
  kind: string;
  line: number;
}

interface SymbolEntry {
  name: string;
  kind: string;
  line: number;
  exported: boolean;
  signature: string;
  members?: ClassMember[];
}

interface ImportEntry {
  from: string;
  names: string[];
}

interface ReExportEntry {
  from: string;
  names: string[] | '*';
  typeOnly: boolean;
}

interface FileEntry {
  path: string;
  symbols: SymbolEntry[];
  imports: ImportEntry[];
  reExports: ReExportEntry[];
}

interface Output {
  schema: string;
  repo: { name: string; version: string };
  sourceHash: string;
  entrypoints: string[];
  publicApi: PublicApiEntry[];
  files: FileEntry[];
}

function loadConfig(): CodemapConfig {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(`codemap.config.json not found at ${CONFIG_PATH}`);
  }
  const raw = readFileSync(CONFIG_PATH, 'utf8');
  const parsed = JSON.parse(raw) as Partial<CodemapConfig>;
  return {
    sourceDirs: parsed.sourceDirs ?? ['src'],
    entrypoints: parsed.entrypoints ?? ['src/index.ts'],
    exclude: parsed.exclude ?? [],
    maxSignatureLength: parsed.maxSignatureLength ?? 200,
  };
}

function loadPackageJson(repoRoot: string): { name: string; version: string } {
  const pkgPath = join(repoRoot, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;
  return { name: pkg.name ?? 'unknown', version: pkg.version ?? '0.0.0' };
}

function toPosix(p: string): string {
  return p.split(sep).join('/');
}

function compileGlob(pattern: string): RegExp {
  let out = '';
  for (let i = 0; i < pattern.length; i++) {
    const c = pattern[i];
    if (c === '*' && pattern[i + 1] === '*') {
      if (pattern[i + 2] === '/') {
        out += '(?:.*/)?';
        i += 2;
      } else {
        out += '.*';
        i += 1;
      }
    } else if (c === '*') {
      out += '[^/]*';
    } else if (c === '?') {
      out += '[^/]';
    } else if ('.+^$()|[]{}\\'.includes(c)) {
      out += '\\' + c;
    } else {
      out += c;
    }
  }
  return new RegExp(`^${out}$`);
}

function makeMatcher(patterns: string[]): (relPath: string) => boolean {
  const regexes = patterns.map(compileGlob);
  return (p) => regexes.some((r) => r.test(p));
}

function gitLsFiles(repoRoot: string, dir: string): string[] | null {
  try {
    const out = execFileSync('git', ['ls-files', '-z', '--', dir], {
      cwd: repoRoot,
      encoding: 'buffer',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return out
      .toString('utf8')
      .split('\0')
      .filter((s) => s.length > 0);
  } catch {
    return null;
  }
}

function plainWalk(repoRoot: string, dir: string): string[] {
  const out: string[] = [];
  const abs = join(repoRoot, dir);
  if (!existsSync(abs)) return out;
  const stack: string[] = [abs];
  while (stack.length > 0) {
    const current = stack.pop() as string;
    for (const entry of readdirSync(current)) {
      const full = join(current, entry);
      const st = statSync(full);
      if (st.isDirectory()) {
        stack.push(full);
      } else if (st.isFile()) {
        out.push(toPosix(relative(repoRoot, full)));
      }
    }
  }
  return out;
}

function discoverSourceFiles(config: CodemapConfig, repoRoot: string): string[] {
  const isExcluded = makeMatcher(config.exclude);
  const seen = new Set<string>();
  for (const dir of config.sourceDirs) {
    const fromGit = gitLsFiles(repoRoot, dir);
    const listed = fromGit ?? plainWalk(repoRoot, dir);
    for (const raw of listed) {
      const rel = toPosix(raw);
      if (!rel.endsWith('.ts')) continue;
      if (rel.endsWith('.d.ts') && !rel.startsWith('src/types/')) continue;
      if (isExcluded(rel)) continue;
      seen.add(rel);
    }
  }
  return [...seen].sort();
}

function computeSourceHash(repoRoot: string, files: string[]): string {
  const hash = createHash('sha256');
  for (const f of files) {
    const content = readFileSync(join(repoRoot, f));
    hash.update(f);
    hash.update('\0');
    hash.update(content);
    hash.update('\0');
  }
  return hash.digest('hex');
}

function normalizeWhitespace(text: string): string {
  // Tokenize via ts.Scanner so string literals and template literals survive intact.
  const scanner = ts.createScanner(ts.ScriptTarget.ES2024, /*skipTrivia*/ false);
  scanner.setText(text);
  const parts: string[] = [];
  let lastWasSpace = false;
  while (true) {
    const kind = scanner.scan();
    if (kind === ts.SyntaxKind.EndOfFileToken) break;
    if (
      kind === ts.SyntaxKind.WhitespaceTrivia ||
      kind === ts.SyntaxKind.NewLineTrivia ||
      kind === ts.SyntaxKind.SingleLineCommentTrivia ||
      kind === ts.SyntaxKind.MultiLineCommentTrivia
    ) {
      if (!lastWasSpace && parts.length > 0) {
        parts.push(' ');
        lastWasSpace = true;
      }
      continue;
    }
    parts.push(scanner.getTokenText());
    lastWasSpace = false;
  }
  return parts.join('').trim();
}

function truncate(text: string, max: number): string {
  return text.length > max ? text.slice(0, max) + '…' : text;
}

function sliceSignature(node: ts.Node, sourceFile: ts.SourceFile): string {
  // Strip leading JSDoc/decorator trivia by starting at the modifier-bearing position.
  const start = node.getStart(sourceFile);
  const hasBody =
    (ts.isFunctionDeclaration(node) ||
      ts.isMethodDeclaration(node) ||
      ts.isConstructorDeclaration(node) ||
      ts.isGetAccessorDeclaration(node) ||
      ts.isSetAccessorDeclaration(node)) &&
    node.body !== undefined;
  if (hasBody) {
    const body = (node as ts.FunctionLikeDeclaration).body!;
    return sourceFile.text.slice(start, body.getStart(sourceFile));
  }
  if (ts.isClassDeclaration(node)) {
    const text = sourceFile.text.slice(start, node.getEnd());
    const braceIdx = text.indexOf('{');
    return braceIdx >= 0 ? text.slice(0, braceIdx) : text;
  }
  return sourceFile.text.slice(start, node.getEnd());
}

function buildSignature(
  node: ts.Node,
  sourceFile: ts.SourceFile,
  config: CodemapConfig,
): string {
  return truncate(normalizeWhitespace(sliceSignature(node, sourceFile)), config.maxSignatureLength);
}

function buildVariableSignature(
  stmt: ts.VariableStatement,
  decl: ts.VariableDeclaration,
  sourceFile: ts.SourceFile,
  config: CodemapConfig,
): string {
  const modifiers = ts.canHaveModifiers(stmt)
    ? (ts.getModifiers(stmt) ?? []).map((m) => m.getText(sourceFile)).join(' ')
    : '';
  const kindKeyword =
    (stmt.declarationList.flags & ts.NodeFlags.Const) !== 0
      ? 'const'
      : (stmt.declarationList.flags & ts.NodeFlags.Let) !== 0
        ? 'let'
        : 'var';
  const namePart = decl.name.getText(sourceFile);
  const typePart = decl.type ? `: ${decl.type.getText(sourceFile)}` : '';
  const head = [modifiers, kindKeyword, namePart + typePart].filter(Boolean).join(' ');
  return truncate(normalizeWhitespace(head), config.maxSignatureLength);
}

function collectJsDocText(comment: ts.JSDoc['comment']): string {
  if (!comment) return '';
  if (typeof comment === 'string') return comment;
  return comment.map((c) => c.text).join('');
}

function collectTagText(comment: ts.JSDocTag['comment']): string {
  if (!comment) return '';
  if (typeof comment === 'string') return comment;
  return comment
    .map((c) => {
      if ('text' in c) return c.text;
      return '';
    })
    .join('');
}

function extractJsDoc(node: ts.Node): string | undefined {
  const all = ts.getJSDocCommentsAndTags(node);
  if (all.length === 0) return undefined;
  let description = '';
  const tagsOrdered: { name: string; text: string }[] = [];
  for (const item of all) {
    if (ts.isJSDoc(item)) {
      if (!description) description = collectJsDocText(item.comment);
      if (item.tags) {
        for (const tag of item.tags) {
          tagsOrdered.push({ name: tag.tagName.text, text: collectTagText(tag.comment) });
        }
      }
    }
  }
  const firstPara = description.split(/\r?\n\r?\n/)[0].replace(/\s+/g, ' ').trim();
  const inlineParts: string[] = [];
  let exampleSeen = false;
  for (const tag of tagsOrdered) {
    if (tag.name === 'param' || tag.name === 'returns' || tag.name === 'return') continue;
    if (tag.name === 'example') {
      if (exampleSeen) continue;
      exampleSeen = true;
      const truncated = truncate(tag.text.replace(/\s+/g, ' ').trim(), MAX_EXAMPLE_LENGTH);
      inlineParts.push(`@example ${truncated}`.trim());
    } else if (tag.name === 'deprecated' || tag.name === 'since') {
      const cleaned = tag.text.replace(/\s+/g, ' ').trim();
      inlineParts.push(cleaned ? `@${tag.name} ${cleaned}` : `@${tag.name}`);
    }
  }
  const combined = [firstPara, ...inlineParts].filter((s) => s.length > 0).join(' ');
  if (!combined) return undefined;
  return truncate(combined, MAX_JSDOC_LENGTH);
}

function hasExportModifier(node: ts.Node): boolean {
  if (!ts.canHaveModifiers(node)) return false;
  const mods = ts.getModifiers(node);
  return mods?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) ?? false;
}

function lineOf(node: ts.Node, sourceFile: ts.SourceFile): number {
  return sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1;
}

function extractClassMembers(
  node: ts.ClassDeclaration,
  sourceFile: ts.SourceFile,
): ClassMember[] {
  const members: ClassMember[] = [];
  for (const m of node.members) {
    let kind: string | undefined;
    let name: string | undefined;
    if (ts.isConstructorDeclaration(m)) {
      kind = 'constructor';
      name = 'constructor';
    } else if (ts.isMethodDeclaration(m) && m.name) {
      kind = 'method';
      name = m.name.getText(sourceFile);
    } else if (ts.isPropertyDeclaration(m) && m.name) {
      kind = 'property';
      name = m.name.getText(sourceFile);
    } else if (ts.isGetAccessorDeclaration(m) && m.name) {
      kind = 'getter';
      name = m.name.getText(sourceFile);
    } else if (ts.isSetAccessorDeclaration(m) && m.name) {
      kind = 'setter';
      name = m.name.getText(sourceFile);
    }
    if (kind && name) members.push({ name, kind, line: lineOf(m, sourceFile) });
  }
  return members.sort((a, b) => a.line - b.line || a.name.localeCompare(b.name));
}

function parseImport(stmt: ts.ImportDeclaration): ImportEntry | null {
  if (!ts.isStringLiteral(stmt.moduleSpecifier)) return null;
  const from = stmt.moduleSpecifier.text;
  const names: string[] = [];
  if (stmt.importClause) {
    if (stmt.importClause.name) names.push(stmt.importClause.name.text);
    const bindings = stmt.importClause.namedBindings;
    if (bindings) {
      if (ts.isNamespaceImport(bindings)) {
        names.push(`* as ${bindings.name.text}`);
      } else {
        for (const spec of bindings.elements) {
          names.push(
            spec.propertyName
              ? `${spec.propertyName.text} as ${spec.name.text}`
              : spec.name.text,
          );
        }
      }
    }
  }
  return { from, names: names.sort() };
}

function parseReExport(stmt: ts.ExportDeclaration): ReExportEntry | null {
  if (!stmt.moduleSpecifier || !ts.isStringLiteral(stmt.moduleSpecifier)) return null;
  const from = stmt.moduleSpecifier.text;
  const typeOnly = stmt.isTypeOnly;
  let names: string[] | '*';
  if (!stmt.exportClause) {
    names = '*';
  } else if (ts.isNamedExports(stmt.exportClause)) {
    names = stmt.exportClause.elements
      .map((spec) =>
        spec.propertyName ? `${spec.propertyName.text} as ${spec.name.text}` : spec.name.text,
      )
      .sort();
  } else {
    names = '*';
  }
  return { from, names, typeOnly };
}

function isTypeOnlyDeclaration(node: ts.Node): boolean {
  return ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node);
}

function declarationKind(node: ts.Node): string {
  if (ts.isFunctionDeclaration(node)) return 'function';
  if (ts.isClassDeclaration(node)) return 'class';
  if (ts.isInterfaceDeclaration(node)) return 'interface';
  if (ts.isTypeAliasDeclaration(node)) return 'type';
  if (ts.isEnumDeclaration(node)) return 'enum';
  if (ts.isMethodDeclaration(node)) return 'method';
  if (ts.isMethodSignature(node)) return 'method';
  if (ts.isPropertyDeclaration(node)) return 'property';
  if (ts.isGetAccessorDeclaration(node)) return 'getter';
  if (ts.isSetAccessorDeclaration(node)) return 'setter';
  if (ts.isVariableDeclaration(node)) return 'variable';
  if (ts.isConstructorDeclaration(node)) return 'constructor';
  return 'unknown';
}

function extractFile(
  sourceFile: ts.SourceFile,
  relPath: string,
  config: CodemapConfig,
): FileEntry {
  const symbols: SymbolEntry[] = [];
  const imports: ImportEntry[] = [];
  const reExports: ReExportEntry[] = [];
  const exportSpecifierNames = new Set<string>();

  for (const stmt of sourceFile.statements) {
    if (ts.isImportDeclaration(stmt)) {
      const im = parseImport(stmt);
      if (im) imports.push(im);
      continue;
    }
    if (ts.isExportDeclaration(stmt)) {
      if (stmt.moduleSpecifier) {
        const re = parseReExport(stmt);
        if (re) reExports.push(re);
      } else if (stmt.exportClause && ts.isNamedExports(stmt.exportClause)) {
        for (const spec of stmt.exportClause.elements) {
          exportSpecifierNames.add((spec.propertyName ?? spec.name).text);
        }
      }
      continue;
    }
    if (ts.isExportAssignment(stmt)) {
      symbols.push({
        name: 'default',
        kind: 'default',
        line: lineOf(stmt, sourceFile),
        exported: true,
        signature: truncate(
          normalizeWhitespace(stmt.getText(sourceFile)),
          config.maxSignatureLength,
        ),
      });
      continue;
    }
    if (ts.isVariableStatement(stmt)) {
      const exported = hasExportModifier(stmt);
      for (const decl of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(decl.name)) continue;
        symbols.push({
          name: decl.name.text,
          kind: 'variable',
          line: lineOf(decl, sourceFile),
          exported,
          signature: buildVariableSignature(stmt, decl, sourceFile, config),
        });
      }
      continue;
    }
    if (
      ts.isFunctionDeclaration(stmt) ||
      ts.isClassDeclaration(stmt) ||
      ts.isInterfaceDeclaration(stmt) ||
      ts.isTypeAliasDeclaration(stmt) ||
      ts.isEnumDeclaration(stmt)
    ) {
      if (!stmt.name) continue;
      const entry: SymbolEntry = {
        name: stmt.name.text,
        kind: declarationKind(stmt),
        line: lineOf(stmt, sourceFile),
        exported: hasExportModifier(stmt),
        signature: buildSignature(stmt, sourceFile, config),
      };
      if (ts.isClassDeclaration(stmt)) {
        entry.members = extractClassMembers(stmt, sourceFile);
      }
      symbols.push(entry);
      continue;
    }
  }

  for (const sym of symbols) {
    if (!sym.exported && exportSpecifierNames.has(sym.name)) sym.exported = true;
  }

  symbols.sort((a, b) => a.line - b.line || a.name.localeCompare(b.name));
  imports.sort((a, b) => a.from.localeCompare(b.from));
  reExports.sort((a, b) => a.from.localeCompare(b.from));

  return { path: relPath, symbols, imports, reExports };
}

function createProgram(repoRoot: string, srcFiles: string[]): ts.Program {
  const rootNames = srcFiles.map((f) => join(repoRoot, f));
  return ts.createProgram({
    rootNames,
    options: {
      target: ts.ScriptTarget.ES2024,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      allowJs: false,
      noEmit: true,
      skipLibCheck: true,
      strict: false,
    },
  });
}

function publicApiKind(node: ts.Node): string {
  if (ts.isFunctionDeclaration(node)) return 'function';
  if (ts.isClassDeclaration(node)) return 'class';
  if (ts.isInterfaceDeclaration(node)) return 'interface';
  if (ts.isTypeAliasDeclaration(node)) return 'type';
  if (ts.isEnumDeclaration(node)) return 'enum';
  if (ts.isVariableDeclaration(node)) return 'variable';
  return declarationKind(node);
}

function unwrapAlias(checker: ts.TypeChecker, symbol: ts.Symbol): ts.Symbol {
  let current = symbol;
  let depth = 0;
  while ((current.flags & ts.SymbolFlags.Alias) !== 0 && depth < MAX_RESOLUTION_DEPTH) {
    const next = checker.getAliasedSymbol(current);
    if (!next || next === current) break;
    current = next;
    depth += 1;
  }
  return current;
}

function pickDeclaration(symbol: ts.Symbol): ts.Declaration | undefined {
  const decls = symbol.declarations;
  if (!decls || decls.length === 0) return undefined;
  // Prefer declarations with an explicit name we can inspect.
  for (const d of decls) {
    if (
      ts.isFunctionDeclaration(d) ||
      ts.isClassDeclaration(d) ||
      ts.isInterfaceDeclaration(d) ||
      ts.isTypeAliasDeclaration(d) ||
      ts.isEnumDeclaration(d) ||
      ts.isVariableDeclaration(d)
    ) {
      return d;
    }
  }
  return decls[0];
}

function extractPublicApi(
  program: ts.Program,
  config: CodemapConfig,
  repoRoot: string,
): PublicApiEntry[] {
  const checker = program.getTypeChecker();
  const entries: PublicApiEntry[] = [];
  const seen = new Set<string>();
  for (const entry of config.entrypoints) {
    const abs = join(repoRoot, entry);
    const sf = program.getSourceFile(abs);
    if (!sf) continue;
    const moduleSym = checker.getSymbolAtLocation(sf);
    if (!moduleSym) continue;
    for (const exportSym of checker.getExportsOfModule(moduleSym)) {
      const resolved = unwrapAlias(checker, exportSym);
      const decl = pickDeclaration(resolved);
      if (!decl) continue;
      const declSf = decl.getSourceFile();
      const relPath = toPosix(relative(repoRoot, declSf.fileName));
      if (relPath.includes('node_modules/')) continue;
      const line = declSf.getLineAndCharacterOfPosition(decl.getStart(declSf)).line + 1;
      const key = `${exportSym.name}\0${relPath}\0${line}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const signature =
        ts.isVariableDeclaration(decl) && decl.parent && ts.isVariableDeclarationList(decl.parent)
          ? buildVariableSignature(
              decl.parent.parent as ts.VariableStatement,
              decl,
              declSf,
              config,
            )
          : buildSignature(decl, declSf, config);
      const entryOut: PublicApiEntry = {
        name: exportSym.name,
        kind: publicApiKind(decl),
        file: relPath,
        line,
        signature,
        typeOnly: isTypeOnlyDeclaration(decl),
      };
      const jsdoc = extractJsDoc(decl);
      if (jsdoc) entryOut.jsdoc = jsdoc;
      entries.push(entryOut);
    }
  }
  entries.sort(
    (a, b) => a.name.localeCompare(b.name) || a.file.localeCompare(b.file) || a.line - b.line,
  );
  return entries;
}

function buildOutput(repoRoot: string, config: CodemapConfig): Output {
  const files = discoverSourceFiles(config, repoRoot);
  const sourceHash = computeSourceHash(repoRoot, files);
  const repo = loadPackageJson(repoRoot);
  const program = createProgram(repoRoot, files);
  const publicApi = extractPublicApi(program, config, repoRoot);
  const fileEntries: FileEntry[] = [];
  for (const rel of files) {
    const abs = join(repoRoot, rel);
    const sf = program.getSourceFile(abs);
    if (!sf) continue;
    fileEntries.push(extractFile(sf, rel, config));
  }
  fileEntries.sort((a, b) => a.path.localeCompare(b.path));
  return {
    schema: SCHEMA,
    repo,
    sourceHash,
    entrypoints: [...config.entrypoints].sort(),
    publicApi,
    files: fileEntries,
  };
}

function serialize(output: Output): string {
  return MD_PREAMBLE + FENCE_OPEN + JSON.stringify(output, null, 2) + FENCE_CLOSE;
}

function lcsDiff(expected: string, actual: string, maxLines: number): string {
  const expLines = expected.split('\n');
  const actLines = actual.split('\n');
  const m = expLines.length;
  const n = actLines.length;
  // Standard LCS table; bounded by repo size — adequate for ≤150KB outputs.
  const dp: number[][] = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = m - 1; i >= 0; i--) {
    for (let j = n - 1; j >= 0; j--) {
      dp[i][j] =
        expLines[i] === actLines[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
    }
  }
  const out: string[] = [];
  let i = 0;
  let j = 0;
  while (i < m && j < n && out.length < maxLines) {
    if (expLines[i] === actLines[j]) {
      out.push(`  ${expLines[i]}`);
      i++;
      j++;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      out.push(`- ${expLines[i]}`);
      i++;
    } else {
      out.push(`+ ${actLines[j]}`);
      j++;
    }
  }
  while (i < m && out.length < maxLines) {
    out.push(`- ${expLines[i++]}`);
  }
  while (j < n && out.length < maxLines) {
    out.push(`+ ${actLines[j++]}`);
  }
  return out.join('\n');
}

function maybeWarnSize(text: string): void {
  const bytes = Buffer.byteLength(text, 'utf8');
  if (bytes > SIZE_WARN_BYTES) {
    const kb = (bytes / 1024).toFixed(1);
    stderr.write(`warning: CODEMAP.md is ${kb} KB (>${SIZE_WARN_BYTES / 1024} KB sanity bound)\n`);
  }
}

function runGenerate(): void {
  const config = loadConfig();
  const output = buildOutput(REPO_ROOT, config);
  const text = serialize(output);
  writeFileSync(OUTPUT_PATH, text, 'utf8');
  maybeWarnSize(text);
}

function runCheck(): void {
  const config = loadConfig();
  const output = buildOutput(REPO_ROOT, config);
  const expected = serialize(output);
  const actual = existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, 'utf8') : '';
  if (expected === actual) {
    stdout.write('✓ CODEMAP.md is up to date\n');
    exit(0);
  }
  const diff = lcsDiff(expected, actual, 40);
  stderr.write(diff + '\n');
  stderr.write('✗ CODEMAP.md is stale. Run `npm run codemap` and commit the result.\n');
  maybeWarnSize(expected);
  exit(1);
}

function main(): void {
  const isCheck = argv.includes('--check');
  if (isCheck) runCheck();
  else runGenerate();
}

main();
